export const slidesQueue = [
  {
    id: 12,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
  {
    id: 13,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
  {
    id: 14,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
  {
    id: 15,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
  {
    id: 16,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
  {
    id: 17,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
  {
    id: 18,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "./images/photo1.png",
    video: "",
  },
  {
    id: 19,
    text:
      "Этим кибернетическим сообщением в сети «Инстаграмм» я передаю привет в дождливую и холодную Москву из солнечной и летней Сибири. Держитесь, друзья фыов фыв тф  фытвоф втфтвфтв фытв флоывт",
    author: "Иван Иванов",
    network: "fb",
    img: "",
    video: "",
  },
  {
    id: 20,
    text:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates dignissimos et laboriosam doloremque beatae animi labore! Voluptatibus esse ullam veritatis maiores voluptate dignissimos recusandae minima quaerat, doloribus est, excepturi quo.",
    author: "Иван Иванов",
    network: "inst",
    img: "./images/photo2.png",
    video: "",
  },
  {
    id: 21,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "twitter",
    img: "",
    video: "",
  },
  {
    id: 22,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
  {
    id: 23,
    text: "Что отражаем, то и порождаем. Я металлический",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
];

export const initialSlides1 = [
  {
    id: 0,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "./images/photo1.png",
    video: "",
  },
  {
    id: 2,
    text:
      "Этим кибернетическим сообщением в сети «Инстаграмм» я передаю привет в дождливую и холодную Москву из солнечной и летней Сибири. Держитесь, друзья фыов фыв тф  фытвоф втфтвфтв фытв флоывт",
    author: "Иван Иванов",
    network: "fb",
    img: "",
    video: "",
  },
  {
    id: 4,
    text:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates dignissimos et laboriosam doloremque beatae animi labore! Voluptatibus esse ullam veritatis maiores voluptate dignissimos recusandae minima quaerat, doloribus est, excepturi quo.",
    author: "Иван Иванов",
    network: "inst",
    img: "./images/photo2.png",
    video: "",
  },
  {
    id: 6,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "twitter",
    img: "",
    video: "",
  },
  {
    id: 8,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "https://akslnklas.asklnkad/asklfnafnas.png",
    video: "",
  },
  {
    id: 10,
    text: "Что отражаем, то и порождаем. Я металлический",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
];

export const initialSlides2 = [
  {
    id: 1,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "fb",
    img: "",
    video: "",
  },
  {
    id: 3,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "./images/photo3.png",
    video: "",
  },
  {
    id: 5,
    text:
      "Правильный чай: шен-пуэр с лимоном из гайвани. Тепла и уюта в в вашу жизнь!",
    author: "Иван Иванов",
    network: "twitter",
    img: "",
    video: "",
  },
  {
    id: 7,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
  {
    id: 9,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "inst",
    img: "./images/photo4.png",
    video: "",
  },
  {
    id: 11,
    text: "По главной yлице пройду — и солнце светит. Обнял всех вас!",
    author: "Иван Иванов",
    network: "vk",
    img: "",
    video: "",
  },
];
